"""The brand review: what a brand manager needs to decide this week, then the evidence.

Reads top to bottom — the verdict, the moves, the brand against its K-beauty rivals, every SKU against
its own product type, a head-to-head drill-down, what moves rank, where to grow the range, which
stores cannot sell us, and review momentum. Every sentence is generated by insights.py from the crawl.
"""
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

import insights as I
from common import (BRANDS_CSV, CLASS_COLORS, FOCUS_HUE, INK, PEER_HUE, competitor_keys, focus_brand, focus_key,
                    get_conn, run_ids, style_fig)

st.set_page_config(page_title="Innisfree on Blinkit", page_icon="🧴", layout="wide")
st.markdown("""<style>
  .block-container{padding-top:2rem;max-width:1180px}
  .kicker{font-size:.78rem;letter-spacing:.08em;text-transform:uppercase;color:#898781;margin:0 0 .15rem}
  .verdict li{margin:.35rem 0;font-size:1.02rem;line-height:1.5}
  .headline{font-size:1.06rem;line-height:1.55;margin:.2rem 0 .8rem;color:#1f2933}
  .move{font-weight:600;font-size:1rem;margin:.1rem 0 .3rem;color:#0b0b0b}
  .why{color:#52514e;font-size:.9rem;line-height:1.45;margin:0}
  .area{font-size:.72rem;letter-spacing:.06em;text-transform:uppercase;color:#52514e;font-weight:600;margin:0}
  .affects{font-size:.75rem;color:#898781;margin:.35rem 0 0}
</style>""", unsafe_allow_html=True)

ids = run_ids()
if not ids:
    st.title("Blinkit beauty")
    st.warning("No crawl data yet — run `python scrape.py`.")
    st.stop()

with st.sidebar:
    run_id = st.selectbox("Crawl", ids, format_func=lambda r: f"{r}{'  (latest)' if r == ids[0] else ''}")
    st.caption(f"Focus · **{focus_brand()}**")
    st.caption("Every product, brand classification and data quality live on **Explore & data**.")

FB, FK = focus_brand(), focus_key()
GREY = "#d9d8d2"


@st.cache_data(ttl=900, show_spinner="Analysing the crawl…")
def build(run_id: str, prev_id: str | None, brands_mtime: float, fk: str, pk: tuple, fname: str) -> dict:
    ctx = I.Ctx(get_conn(), run_id, fk, list(pk), fname)
    p = I.products(ctx)
    r = {"trust": I.trust(ctx), "p": p, "pins": ctx.pins, "skus": I.sku_table(ctx, p), "sc": I.scorecard(ctx, p),
         "dr": I.rank_drivers(ctx, p), "ws": I.whitespace(ctx, p), "sg": I.store_gaps(ctx)}
    r["ops"] = I.actions(ctx, r["skus"], r["sc"], r["ws"], r["sg"], r["dr"])
    r["mom"] = None
    if prev_id:
        pctx = I.Ctx(get_conn(), prev_id, fk, list(pk), fname)
        r["mom"] = I.momentum(p, I.products(pctx), fk)
    return r


pos = ids.index(run_id)
prev_id = ids[pos + 1] if pos + 1 < len(ids) else None
mtime = BRANDS_CSV.stat().st_mtime if BRANDS_CSV.exists() else 0.0
R = build(run_id, prev_id, mtime, FK, tuple(competitor_keys()), FB)
tr, P, PINS, SK, SC, DR, WS, SG = (R[k] for k in ("trust", "p", "pins", "skus", "sc", "dr", "ws", "sg"))
s = tr["s"]


def section(n: int, title: str, headline: str):
    st.divider()
    st.markdown(f'<p class="kicker">{n:02d}</p>', unsafe_allow_html=True)
    st.subheader(title)
    st.markdown(f'<p class="headline">{headline}</p>', unsafe_allow_html=True)


def rupees(v) -> str:
    return "–" if pd.isna(v) else f"₹{v:,.0f}"


# ============================================================================ header
st.title(f"{FB} on Blinkit")
st.caption(f"Brand review · Skincare + Makeup · crawl `{run_id}` · {int(s.pincodes)} stores across {int(s.cities)} "
           f"metros · {int(s.cards):,} shelf listings · {int(s.brands)} brands")
ok = sum(c[1] for c in tr["checks"])
with st.expander(f"{'✅' if tr['all_ok'] else '⚠️'}  Data verified — {ok} of {len(tr['checks'])} integrity checks pass. "
                 "What was checked, and what this data cannot tell you", expanded=not tr["all_ok"]):
    st.dataframe(pd.DataFrame(tr["checks"], columns=["check", "passed", "result"]), hide_index=True,
                 width="stretch", column_config={"passed": st.column_config.CheckboxColumn("pass")})
    for cv in tr["caveats"]:
        st.markdown(f"- {cv}")

if not len(SK):
    st.warning(f"**{FB} is not listed in this crawl.** Nothing to review.")
    st.stop()

f = SC["focus"]
k = SC["k"]
n_sku = len(SK)
wins = SK[SK["winning"]]
over = SK[SK["flags"].map(lambda x: "Reprice / repack" in x)]
sell_pct = SK["sellable"].sum() / SK["stores"].sum() * 100
stp = SG["stores"]

# ============================================================================ verdict
st.markdown('<p class="kicker">The verdict</p>', unsafe_allow_html=True)
lead_k = k.iloc[0]
bullets = [
    f"**{FB} earns {f.demand_share:.1f}% of K-beauty's reviews on Blinkit — #{f.demand_rank} of {SC['n_k']} Korean "
    f"brands.** {lead_k['brand']} earns {lead_k['demand_share']:.0f}%"
    + (f", and {k.iloc[1]['brand']} {k.iloc[1]['demand_share']:.0f}%." if len(k) > 1 else ".")
]
if len(wins):
    w = wins.iloc[0]
    bullets.append(f"**{len(wins)} of {n_sku} SKUs win their product type.** {w['sku']} ({w['unit']}) ranks "
                   f"#{w['rank_in_group']} of {w['group_n']} in {w['group'].lower()} at ₹{w['price']:,.0f}"
                   + (" — a small, affordable pack." if w["price"] <= w["bench_price"] else "."))
else:
    bullets.append(f"**None of {n_sku} SKUs wins its product type** (top quarter and top {I.TOP} of its peers).")
if len(over):
    g = over.groupby("group").agg(n=("sku", "size"), idx=("ticket_idx", "median"), price=("price", "median"),
                                  bench=("bench_price", "median")).sort_values("n", ascending=False)
    g0 = g.iloc[0]
    bullets.append(f"**{len(over)} of {n_sku} SKUs are priced ≥{I.PRICE_FLAG}× the products that win their type.** "
                   f"The biggest block is {int(g0.n)} {g.index[0].lower()} SKU{'s' if g0.n > 1 else ''} at "
                   f"₹{g0.price:,.0f}, against ₹{g0.bench:,.0f} for the best-ranked.")
if len(stp):
    lo, hi = stp.iloc[0], stp.iloc[-1]
    bullets.append(f"**Shoppers can buy {sell_pct:.0f}% of the range where it is listed — but not evenly.** "
                   f"{lo['area']} ({lo['city']}) can sell {int(lo['sellable'])} of {SG['n_skus']} SKUs; "
                   f"{hi['area']} can sell {int(hi['sellable'])}.")
med = DR["median"]
if len(med):
    bullets.append(f"**Reviews move rank; discounts don't.** In a typical sub-category a one-step rise in reviews lifts "
                   f"a product {med.get('Review count', 0):+.0f} percentile points up its shelf; a deeper discount "
                   f"scores {med.get('Discount depth', 0):+.0f} once reviews are accounted for.")
st.markdown('<ul class="verdict">' + "".join(
    f"<li>{b.replace('**', '<b>', 1).replace('**', '</b>', 1)}</li>" for b in bullets) + "</ul>", unsafe_allow_html=True)

m = st.columns(5)
m[0].metric("Share of K-beauty reviews", f"{f.demand_share:.1f}%", help="Our reviews ÷ all Korean brands' reviews, "
            "counted once per product family. The closest proxy to share of K-beauty sales.")
m[1].metric("SKUs winning their type", f"{len(wins)} / {n_sku}",
            help=f"Ranked in the top quarter (and top {I.TOP}) of widely listed products of the same type.")
m[2].metric("SKUs overpriced vs winners", f"{len(over)} / {n_sku}",
            help=f"Ticket price and price per g/ml both ≥{I.PRICE_FLAG}× the median of the {I.TOP} best-ranked "
                 "products of the same type.")
m[3].metric("Sellable where listed", f"{sell_pct:.0f}%", help="Store listings where a shopper can buy some size today.")
m[4].metric("Median rating", f"{SK['rating'].median():.1f}★",
            help=f"Median across rated {FB} SKUs.")

# ============================================================================ 01 actions
section(1, "What to do this week",
        f"Ranked by how many store listings each move touches. Every move names its SKUs and the rival "
        f"that sets the bar.")
ops = R["ops"]
if not ops:
    st.success("No gaps flagged.")


def cards(items):
    for i in range(0, len(items), 2):
        cols = st.columns(2)
        for col, o in zip(cols, items[i:i + 2]):
            with col.container(border=True):
                st.markdown(f'<p class="area">{o["area"]}</p><p class="move">{o["move"]}</p>'
                            f'<p class="why">{o["why"]}</p><p class="affects">Touches {o["affects"]} store '
                            f'listing{"s" if o["affects"] != 1 else ""}</p>', unsafe_allow_html=True)


SHOW = 8
cards(ops[:SHOW])
if len(ops) > SHOW:
    with st.expander(f"{len(ops) - SHOW} smaller moves"):
        cards(ops[SHOW:])

# ============================================================================ 02 field
t = SC["t"]
# Compare win rate only among brands with a real range: 1 winner out of 3 products is 33% and would
# make any brand with a full range look second-rate.
ranged = t[(t["products"] >= 5) & (t["brand_key"] != FK)].sort_values("win_rate", ascending=False)
best_w = ranged.iloc[0] if len(ranged) else t.sort_values("win_rate", ascending=False).iloc[0]
section(2, f"{FB} against the K-beauty brands that matter",
        f"The {len(t)} brands below are {FB}'s named competitors plus the K-brands earning the most reviews. "
        f"{t.iloc[0]['brand']} leads with <b>{t.iloc[0]['demand_share']:.0f}%</b> of K-beauty reviews from "
        f"{int(t.iloc[0]['products'])} products; {FB} has <b>{f.demand_share:.1f}%</b> from {int(f.products)}. "
        f"{FB} wins its type with <b>{int(f.winning)}</b> product{'s' if f.winning != 1 else ''} "
        f"({f.win_rate:.0f}% of its range), against {best_w['brand']}'s {int(best_w['winning'])} of "
        f"{int(best_w['products'])} ({best_w['win_rate']:.0f}%).")
c1, c2 = st.columns([2, 3])
with c1:
    d = t.sort_values("demand_share")
    fig = go.Figure(go.Bar(x=d["demand_share"], y=d["brand"], orientation="h",
                           marker=dict(color=[FOCUS_HUE if b == FK else PEER_HUE for b in d["brand_key"]], line=dict(width=0)),
                           text=[f"{v:.1f}%" for v in d["demand_share"]], textposition="outside", cliponaxis=False,
                           textfont=dict(color=INK["secondary"]),
                           hovertemplate="%{y}: %{x:.1f}% of K-beauty reviews<extra></extra>"))
    fig.update_xaxes(title="share of K-beauty reviews (%)", range=[0, float(d["demand_share"].max()) * 1.25])
    fig.update_yaxes(title=None)
    st.plotly_chart(style_fig(fig, height=40 * len(d) + 70, legend=False, xgrid=True), width="stretch")
with c2:
    st.dataframe(t[["brand", "products", "winning", "win_rate", "sellable_pct", "median_price", "on_offer",
                    "median_reviews", "rating"]], hide_index=True, width="stretch",
                 column_config={
                     "winning": st.column_config.NumberColumn("SKUs winning", help="Top quarter of their product type."),
                     "win_rate": st.column_config.NumberColumn("win rate", format="%.0f%%"),
                     "sellable_pct": st.column_config.ProgressColumn("sellable", min_value=0, max_value=100, format="%.0f%%"),
                     "median_price": st.column_config.NumberColumn("median ₹", format="₹%.0f"),
                     "on_offer": st.column_config.NumberColumn("on offer", format="%.0f%%"),
                     "median_reviews": st.column_config.NumberColumn("median reviews", format="%.0f"),
                     "rating": st.column_config.NumberColumn("rating", format="%.1f★")})
    st.caption("Win rate = share of the brand's products ranked in the top quarter of their type. "
               "Sellable = store listings a shopper can buy today.")

# ============================================================================ 03 SKU scorecard
section(3, "Every SKU, judged against its own product type",
        f"Each {FB} SKU is compared with the {I.TOP} best-ranked, widely listed products of the same Blinkit product "
        f"type. <b>{len(wins)}</b> win, <b>{len(over)}</b> are priced ≥{I.PRICE_FLAG}× those winners, and "
        f"<b>{int((SK['sellable_pct'] < I.STOCK_FLAG).sum())}</b> are sellable in under {I.STOCK_FLAG}% of the stores "
        f"that list them.")
c1, c2 = st.columns([3, 2])
with c1:
    d = SK.copy()
    d["x"] = d["ticket_idx"]
    d["y"] = d["rank_in_group"] / d["group_n"] * 100
    # Labels only where they carry the story — a winner, or a block of same-type SKUs priced alike —
    # so they never collide in the dense middle. Every other dot is identified on hover and in the
    # table below.
    first = d.sort_values("rank_in_group").drop_duplicates("group").index
    cnt = d.groupby("group")["sku"].transform("size")
    d["lab"] = ""
    keep = [i for i in first if cnt.loc[i] > 1 or d.loc[i, "winning"]]
    d.loc[keep, "lab"] = [(f"{d.loc[i, 'group']} ×{cnt.loc[i]}" if cnt.loc[i] > 1 else d.loc[i, "sku"][:22])
                          for i in keep]
    xmax = max(float(d["x"].max()) * 1.5, 3)
    fig = go.Figure()
    fig.add_shape(type="rect", x0=I.PRICE_FLAG, x1=xmax, y0=25, y1=102, fillcolor="#f4f3ef", line_width=0, layer="below")
    fig.add_vline(x=1, line_dash="dot", line_color=INK["axis"])
    fig.add_hline(y=25, line_dash="dot", line_color=INK["axis"])
    # Region notes sit in the empty upper-right, clear of the dots and their labels.
    fig.add_annotation(xref="paper", x=1, y=24, xanchor="right", yanchor="bottom", showarrow=False,
                       text="top quarter of its type ↑", font=dict(size=11, color=INK["muted"]))
    fig.add_annotation(xref="paper", x=1, y=27, xanchor="right", yanchor="top", showarrow=False,
                       text="↓ priced ≥1.5× the winners and outside the top quarter", font=dict(size=11, color=INK["muted"]))
    fig.add_trace(go.Scatter(
        x=d["x"], y=d["y"], mode="markers+text", text=d["lab"],
        textposition="middle right",
        textfont=dict(size=11, color=INK["secondary"]),
        marker=dict(size=[max(9, min(26, st_ * 0.9)) for st_ in d["stores"]], color=FOCUS_HUE,
                    line=dict(width=2, color="#ffffff")),
        customdata=np.stack([d["sku"], d["unit"], d["rank_in_group"], d["group_n"], d["group"], d["price"],
                             d["bench_price"], d["action"], d["stores"]], axis=-1),
        hovertemplate="<b>%{customdata[0]}</b> · %{customdata[1]}<br>#%{customdata[2]} of %{customdata[3]} "
                      "%{customdata[4]}<br>₹%{customdata[5]:,.0f} vs ₹%{customdata[6]:,.0f} for the best-ranked "
                      "(%{x:.2f}×)<br>listed in %{customdata[8]} stores<br>→ %{customdata[7]}<extra></extra>"))
    ticks = [v for v in (0.25, 0.5, 1, 1.5, 2, 3, 5, 10) if v <= xmax]
    fig.update_xaxes(type="log", range=[np.log10(0.35), np.log10(xmax)], tickvals=ticks,
                     ticktext=[f"{v:g}×" for v in ticks], title="ticket price ÷ median of the type's best-ranked products")
    fig.update_yaxes(range=[102, -2], title="rank within its type (percentile, top = best)")
    st.plotly_chart(style_fig(fig, height=420, legend=False, xgrid=True), width="stretch")
    st.caption("Each dot is one SKU, sized by how many stores list it. Labels mark the best SKU of each type; "
               "hover any dot for its detail.")
with c2:
    counts = SK["action"].value_counts()
    order = ["Widen listing", "Fix stock", "Reprice / repack", "Fix rating", "Build reviews", "Defend & scale", "Hold"]
    st.markdown("**Primary action per SKU**")
    for a in order:
        if a in counts:
            names = SK[SK["action"] == a]
            st.markdown(f"**{a}** · {counts[a]}  \n"
                        + "<span style='color:#52514e;font-size:.88rem'>"
                        + ", ".join(f"{x} ({u})" for x, u in zip(names["sku"].str.slice(0, 34), names["unit"]))
                        + "</span>", unsafe_allow_html=True)
    st.caption("One primary action per SKU: distribution and stock first (a shopper cannot buy it), then price, "
               "rating and reviews. A SKU in the top quarter of its type is marked Defend & scale.")

tbl = SK.copy()
tbl["rank"] = [f"#{a} of {b}" for a, b in zip(tbl["rank_in_group"], tbl["group_n"])]
tbl["sellable_str"] = [f"{a} / {b}" for a, b in zip(tbl["sellable"], tbl["stores"])]
tbl["rival"] = [("–" if x is None else f"{x['brand']} · ₹{x['price']:,.0f} · {x['unit']} · "
                 f"{0 if pd.isna(x['reviews']) else x['reviews']:,.0f} rev") for x in tbl["lead"]]
tbl["flags_str"] = tbl["flags"].map(lambda x: ", ".join(x) if x else "–")
st.dataframe(
    tbl[["action", "sku", "unit", "group", "rank", "sellable_str", "price", "bench_price", "ticket_idx", "disc",
         "reviews", "bench_reviews", "rating", "rival", "flags_str"]],
    hide_index=True, width="stretch", height=35 * len(tbl) + 38,
    column_config={
        "action": st.column_config.TextColumn("primary action"), "sku": st.column_config.TextColumn("SKU", width="medium"),
        "group": "product type", "rank": st.column_config.TextColumn("rank in type"),
        "sellable_str": st.column_config.TextColumn("sellable / listed", help="Stores where a shopper can buy it."),
        "price": st.column_config.NumberColumn("our ₹", format="₹%.0f"),
        "bench_price": st.column_config.NumberColumn("winners' ₹", format="₹%.0f",
                                                     help=f"Median price of the {I.TOP} best-ranked products of the type."),
        "ticket_idx": st.column_config.NumberColumn("price ×", format="%.2f×"),
        "disc": st.column_config.NumberColumn("our disc", format="%.0f%%"),
        "reviews": st.column_config.NumberColumn("our reviews", format="%.0f"),
        "bench_reviews": st.column_config.NumberColumn("winners' reviews", format="%.0f"),
        "rating": st.column_config.NumberColumn("rating", format="%.1f★"),
        "rival": st.column_config.TextColumn("best-ranked rival in type", width="large"),
        "flags_str": st.column_config.TextColumn("all flags", width="medium")})

# ============================================================================ 04 head-to-head
section(4, "Head-to-head: one SKU against the products beating it",
        "Pick a SKU to see its whole product type on one chart — every widely listed product by price and shelf "
        "rank — and a side-by-side with the type leader and the best-ranked K-beauty rival.")
labels = [f"{a} · {u}  —  {act}" for a, u, act in zip(SK["sku"], SK["unit"], SK["action"])]
# Open on the most widely listed SKU that needs repricing — the head-to-head that matters most.
rp_rows = SK.index[SK["action"] == "Reprice / repack"]
default = int(SK.loc[rp_rows, "stores"].idxmax()) if len(rp_rows) else 0
pick = st.selectbox("SKU", range(len(SK)), index=default, format_func=lambda i: labels[i],
                    label_visibility="collapsed")
r = SK.iloc[pick]
row = P[P["product_id"] == r["product_id"]].iloc[0]
grp = I.peer_group(P, row)
if r["product_id"] not in set(grp["product_id"]):
    grp = pd.concat([grp, P[P["product_id"] == r["product_id"]]])
c1, c2 = st.columns([3, 2])
with c1:
    cut = grp.nsmallest(I.TOP, "med_rank")["med_rank"].max()
    fig = go.Figure()
    fig.add_hrect(y0=0, y1=cut, fillcolor="#f4f3ef", line_width=0, layer="below")
    fig.add_annotation(xref="paper", x=1, y=0, yanchor="top", xanchor="right", showarrow=False,
                       text=f"the {I.TOP} best-ranked", font=dict(size=11, color=INK["muted"]))
    groups = [("Other brands", grp[(grp["cls"] != "Korean") & (grp["brand_key"] != FK)], GREY, 8),
              ("K-beauty rivals", grp[(grp["cls"] == "Korean") & (grp["brand_key"] != FK)], CLASS_COLORS["Korean"], 10),
              (FB, grp[grp["brand_key"] == FK], FOCUS_HUE, 13)]
    for name, g, colr, size in groups:
        if not len(g):
            continue
        fig.add_trace(go.Scatter(
            x=g["price"], y=g["med_rank"], mode="markers", name=name,
            marker=dict(size=size, color=colr, line=dict(width=1.5, color="#ffffff")),
            customdata=np.stack([g["brand"], [I.short_name(a, b)[:48] for a, b in zip(g["product"], g["brand"])],
                                 g["unit"].fillna(""), g["reviews"].fillna(0), g["disc"], g["stores"]], axis=-1),
            hovertemplate="<b>%{customdata[0]}</b> %{customdata[1]} · %{customdata[2]}<br>₹%{x:,.0f} · "
                          "%{customdata[4]:.0f}% off<br>median rank %{y:.0f} · %{customdata[3]:,.0f} reviews · "
                          "%{customdata[5]} stores<extra></extra>"))
    marks = [(f"{FB} · ₹{r['price']:,.0f}", r["price"], r["med_rank"], FOCUS_HUE)]
    seen = {r["product_id"]}
    for x, tag in ((r["lead"], "leader"), (r["k_rival"], "best K-beauty")):
        if x is not None and (x["brand"], x["price"], x["rank"]) not in {(m_[0], m_[1], m_[2]) for m_ in marks}:
            marks.append((f"{tag}: {x['brand']} · ₹{x['price']:,.0f}", x["price"], x["rank"], INK["secondary"]))
    # Callouts point down-right into the chart: the leaders sit at the very top, where an upward label
    # would be clipped by the plot edge.
    for i_, (txt, x_, y_, colr) in enumerate(marks):
        fig.add_annotation(x=np.log10(x_), y=y_, text=txt[:40], showarrow=True, arrowhead=0, arrowcolor=INK["axis"],
                           ax=50, ay=30 + 22 * i_, xanchor="left", font=dict(size=11, color=colr),
                           bgcolor="rgba(255,255,255,.85)")
    tv = [v for v in (10, 20, 50, 100, 200, 500, 1000, 2000, 5000)
          if grp["price"].min() / 1.6 <= v <= grp["price"].max() * 1.6]
    fig.update_xaxes(type="log", tickvals=tv, ticktext=[f"₹{v:,}" for v in tv], title="price (log scale)")
    fig.update_yaxes(range=[float(grp["med_rank"].max()) * 1.05, -3], title="median shelf rank (top = best)")
    st.plotly_chart(style_fig(fig, height=420, xgrid=True), width="stretch")
    st.caption(f"{r['group']}: {len(grp)} products listed in at least {int(round(PINS * I.WIDE))} stores. "
               "The shaded band is where the best-ranked products sit.")
with c2:
    def col(x, is_us=False):
        if x is None:
            return ["–"] * 9
        pu = x["p_unit"]
        return [x["brand"] if not is_us else FB, str(x["unit"]), rupees(x["price"]),
                "–" if pd.isna(pu) else f"₹{pu:,.1f} / {'g·ml' if x['kind'] == 'g/ml' else 'pc'}",
                f"{x['disc']:.0f}%", f"{0 if pd.isna(x['reviews']) else x['reviews']:,.0f}",
                "–" if pd.isna(x["rating"]) else f"{x['rating']:.1f}★", f"{x['rank']:.0f}", f"{int(x['stores'])}"]

    us = {"brand": FB, "unit": r["unit"], "price": r["price"], "p_unit": r["p_unit"], "kind": r["kind"], "disc": r["disc"],
          "reviews": r["reviews"], "rating": r["rating"], "rank": r["med_rank"], "stores": r["stores"]}
    bench = ["", "", f"₹{r['bench_lo']:,.0f}–{r['bench_hi']:,.0f}",
             "–" if pd.isna(r["bench_punit"]) else f"₹{r['bench_punit']:,.1f}", f"{r['bench_disc']:.0f}%",
             f"{r['bench_reviews']:,.0f}", "–" if pd.isna(r["bench_rating"]) else f"{r['bench_rating']:.1f}★",
             f"≤ {cut:.0f}", ""]
    h2h = pd.DataFrame({"": ["brand", "pack", "price", "per unit", "discount", "reviews", "rating", "median rank",
                             "stores"],
                        "us": col(us, True), "type leader": col(r["lead"]), "best K-beauty": col(r["k_rival"]),
                        f"top {I.TOP} median": bench})
    st.dataframe(h2h, hide_index=True, width="stretch", height=38 * 9 + 40)
    gaps = []
    if pd.notna(r["ticket_idx"]):
        gaps.append(f"priced **{r['ticket_idx']:.1f}×** the winners' median")
    if r["bench_reviews"] > 0:
        gaps.append(f"the winners' median has **{r['bench_reviews'] / max(r['reviews'], 1):.0f}×** our reviews"
                    if r["bench_reviews"] > r["reviews"] else "more reviews than the winners' median")
    gaps.append(f"sellable in **{r['sellable']} of {r['stores']}** listing stores")
    st.markdown(f"**{r['sku']}** is #{r['rank_in_group']} of {r['group_n']}: " + "; ".join(gaps) + ".")

# ============================================================================ 05 rank drivers
med = DR["median"]
if len(med):
    section(5, "What moves a product up the shelf",
            f"Across {DR['n']} sub-categories, a model of shelf rank on five levers explains about "
            f"<b>{DR['r2'] * 100:.0f}%</b> of where products sit. <b>Review count</b> is the strongest lever "
            f"(+{med.get('Review count', 0):.0f} percentile points per step, positive in {DR['agree'].get('Review count', 0)} "
            f"of {DR['n']}), then <b>store coverage</b> (+{med.get('Stores listing it', 0):.0f}). "
            f"<b>Discount depth</b> scores {med.get('Discount depth', 0):+.0f} — once reviews are known, offers do "
            "not buy rank. They may still lift conversion, which this data cannot see.")
    c1, c2 = st.columns([2, 3])
    with c1:
        d = med.sort_values()
        fig = go.Figure(go.Bar(x=d.values, y=d.index, orientation="h",
                               marker=dict(color=[PEER_HUE if v > 0 else GREY for v in d.values], line=dict(width=0)),
                               text=[f"{v:+.0f}" for v in d.values], textposition="outside", cliponaxis=False,
                               textfont=dict(color=INK["secondary"]),
                               hovertemplate="%{y}: %{x:+.1f} percentile points<extra></extra>"))
        lim = float(np.abs(d.values).max()) * 1.35
        fig.add_vline(x=0, line_color=INK["axis"])
        fig.update_xaxes(range=[-lim, lim], title="percentile points of shelf gained per one-step rise")
        fig.update_yaxes(title=None)
        st.plotly_chart(style_fig(fig, height=260, legend=False, xgrid=True), width="stretch")
        st.caption("Median across sub-categories. A 'step' is one standard deviation of that lever within the "
                   "sub-category. Descriptive, not causal — Blinkit's sort may use signals we cannot see.")
    with c2:
        need = SK[SK["bench_reviews"] > SK["reviews"]].copy()
        need["gap"] = need["bench_reviews"] - need["reviews"]
        need = need.sort_values("gap", ascending=False)
        st.markdown("**Review gap to the winners, by SKU**")
        st.dataframe(need[["sku", "unit", "group", "reviews", "bench_reviews", "gap", "rating"]], hide_index=True,
                     width="stretch", height=min(38 * len(need) + 40, 420),
                     column_config={"sku": st.column_config.TextColumn("SKU", width="medium"), "group": "type",
                                    "reviews": st.column_config.NumberColumn("ours", format="%.0f"),
                                    "bench_reviews": st.column_config.NumberColumn(f"top {I.TOP} median", format="%.0f"),
                                    "gap": st.column_config.NumberColumn("reviews to close", format="%.0f"),
                                    "rating": st.column_config.NumberColumn("rating", format="%.1f★")})

# ============================================================================ 06 whitespace
pv, uc = WS["proven"], WS["uncracked"]
if len(pv):
    top_pv = pv.iloc[0]
    absent = pv[pv["focus_skus"] == 0]
    section(6, "Where to grow the range",
            f"K-beauty earns <b>{WS['k_total'] / max(WS['all_total'], 1) * 100:.1f}%</b> of all Skincare and Makeup "
            f"reviews on Blinkit, concentrated in a few types. It is proven in <b>{len(pv)}</b>, led by "
            f"{top_pv['ptype'].lower()} ({top_pv['k_share']:.0f}% of that type's reviews)"
            + (f"; {FB} is absent from {len(absent)} of them, including {', '.join(absent['ptype'].str.lower().head(3))}."
               if len(absent) else ".")
            + (f" The biggest pools — {', '.join(uc['ptype'].str.lower().head(3))} — are almost untouched by K-beauty: "
               "larger prizes, but unproven." if len(uc) else ""))
    tabs = st.tabs([f"Proven for K-beauty ({len(pv)})", f"Big pools K-beauty hasn't cracked ({len(uc)})"])
    cfg = {"ptype": "product type",
           "demand": st.column_config.NumberColumn("all reviews", format="%.0f", help="Total reviews in the type, "
                                                   "one per product family — relative demand."),
           "k_share": st.column_config.ProgressColumn("K-beauty share", min_value=0, max_value=100, format="%.0f%%"),
           "focus_skus": st.column_config.NumberColumn(f"{FB} SKUs"),
           "focus_share_of_k": st.column_config.NumberColumn(f"{FB} share of K", format="%.0f%%"),
           "win_price": st.column_config.NumberColumn("winners' ₹", format="₹%.0f"),
           "win_band": st.column_config.TextColumn("winning price band"),
           "best_k": st.column_config.TextColumn("best K-beauty product", width="large"),
           "best_k_reviews": st.column_config.NumberColumn("its reviews", format="%.0f")}
    for tab, d in zip(tabs, (pv, uc)):
        with tab:
            d = d.copy()
            d["win_band"] = [f"₹{a:,.0f}–{b:,.0f}" if pd.notna(a) else "–" for a, b in zip(d["win_lo"], d["win_hi"])]
            st.dataframe(d[["ptype", "demand", "k_share", "focus_skus", "focus_share_of_k", "win_band", "best_k",
                            "best_k_reviews"]], hide_index=True, width="stretch", column_config=cfg)
    st.caption(f"Winning price band = middle half of prices among the {I.TOP} best-ranked products of the type.")

# ============================================================================ 07 store fix list
mat = SG["matrix"]
if len(mat):
    cw = SG["city"]
    thin = stp[stp["sellable"] <= stp["sellable"].max() / 2]
    section(7, "Store fix list",
            f"The same brand is a different range in every dark store. Shoppers can buy between "
            f"<b>{int(stp['sellable'].min())}</b> and <b>{int(stp['sellable'].max())}</b> of {SG['n_skus']} SKUs. "
            f"<b>{cw.iloc[0]['city']}</b> is weakest on average ({cw.iloc[0]['sellable']:.1f} per store"
            + (f", from {int(cw.iloc[0]['worst'])} to {int(cw.iloc[0]['best'])}" if cw.iloc[0]["worst"] != cw.iloc[0]["best"] else "")
            + f"). <b>{len(thin)}</b> store{'s' if len(thin) != 1 else ''} sell half or less of the best store's range.")
    fill = {I.STATES["ok"]: "#e3f3ea", I.STATES["oos"]: "#fbe0dd", I.STATES["soon"]: "#fcefd2", I.STATES["none"]: "#f1f0ec"}
    ink = {I.STATES["ok"]: "#1c5c3b", I.STATES["oos"]: "#8f2a22", I.STATES["soon"]: "#7a5410", I.STATES["none"]: "#898781"}
    view = mat.copy()
    view.insert(0, "can sell", stp.set_index("store").loc[view.index, "sellable"].astype(int).astype(str)
                + f" / {SG['n_skus']}")
    styled = view.style.map(lambda v: f"background-color:{fill.get(v, '#ffffff')};color:{ink.get(v, INK['primary'])}")
    st.dataframe(styled, width="stretch", height=35 * len(view) + 38)
    st.caption("Thinnest stores first; SKUs ordered by how many stores can sell them. "
               "✓ sellable · ✕ out of stock · … coming soon · — not listed in that store.")

# ============================================================================ 08 momentum
st.divider()
st.markdown('<p class="kicker">08</p>', unsafe_allow_html=True)
st.subheader("Review momentum since the last crawl")
mom = R["mom"]
if mom is None:
    st.info("This is the first crawl, so there is no momentum yet. From the next crawl this section shows which "
            "K-beauty brands and products gained the most reviews that week — the closest signal to sell-through "
            f"Blinkit exposes — and how {FB}'s SKUs moved.")
else:
    b = mom["brands"]
    fr = b[b["brand_key"] == FK]
    st.markdown(f'<p class="headline">K-beauty products gained <b>{b["gain"].sum():,.0f}</b> reviews since '
                f'`{prev_id}`. {b.iloc[0]["brand"]} took <b>{b.iloc[0]["gain_share"]:.0f}%</b> of them; {FB} took '
                f'<b>{float(fr["gain_share"].iloc[0]) if len(fr) else 0:.1f}%</b>.</p>', unsafe_allow_html=True)
    c1, c2 = st.columns(2)
    with c1:
        st.dataframe(b[["brand", "gain", "gain_share", "growth"]].head(10), hide_index=True, width="stretch",
                     column_config={"gain": st.column_config.NumberColumn("new reviews", format="%.0f"),
                                    "gain_share": st.column_config.NumberColumn("share of K gain", format="%.1f%%"),
                                    "growth": st.column_config.NumberColumn("growth", format="%.1f%%")})
    with c2:
        mv = mom["movers"].copy()
        mv["product"] = [I.short_name(a, x) for a, x in zip(mv["product"], mv["brand"])]
        st.dataframe(mv[["brand", "product", "gain", "reviews"]], hide_index=True, width="stretch",
                     column_config={"gain": st.column_config.NumberColumn("new reviews", format="%.0f"),
                                    "reviews": st.column_config.NumberColumn("total", format="%.0f")})
