"""The story page: one scroll from verdict to evidence.

Reads top to bottom — can the data be trusted, what is the verdict, what should we do, then the
evidence for each claim, one section per question. Every sentence is generated by insights.py
from the current crawl, so none of it goes stale when the data refreshes.
"""
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

import insights as I
from common import (BRANDS_CSV, CLASS_COLORS, CLASSES, FOCUS_HUE, INK, PEER_HUE, competitor_keys, focus_brand,
                    focus_key, get_conn, run_ids, style_fig)

st.set_page_config(page_title="Innisfree on Blinkit", page_icon="🧴", layout="wide")
st.markdown("""<style>
  .block-container{padding-top:2rem;max-width:1180px}
  .kicker{font-size:.78rem;letter-spacing:.08em;text-transform:uppercase;color:#898781;margin:0 0 .15rem}
  .verdict li{margin:.35rem 0;font-size:1.02rem;line-height:1.5}
  .headline{font-size:1.08rem;line-height:1.55;margin:.2rem 0 .8rem;color:#1f2933}
  .move{font-weight:600;font-size:1rem;margin:.1rem 0 .25rem}
  .why{color:#52514e;font-size:.9rem;line-height:1.45}
  .area{font-size:.72rem;letter-spacing:.06em;text-transform:uppercase;color:#2a78d6;font-weight:600}
</style>""", unsafe_allow_html=True)

ids = run_ids()
if not ids:
    st.title("Blinkit beauty")
    st.warning("No crawl data yet — run `python scrape.py`.")
    st.stop()

with st.sidebar:
    run_id = st.selectbox("Crawl", ids, format_func=lambda r: f"{r}{'  (latest)' if r == ids[0] else ''}")
    st.caption(f"Focus · **{focus_brand()}**")
    st.caption("Filters and product-level drill-down live on **Explore & data**.")

FB, FK = focus_brand(), focus_key()


@st.cache_data(ttl=900, show_spinner="Analysing the crawl…")
def build(run_id: str, brands_mtime: float, fk: str, pk: tuple, fname: str) -> dict:
    ctx = I.Ctx(get_conn(), run_id, fk, list(pk), fname)
    r = {"trust": I.trust(ctx), "market": I.market(ctx), "kb": I.kbeauty(ctx), "peers": I.peers(ctx),
         "vis": I.visibility(ctx), "av": I.availability(ctx), "pr": I.pricing(ctx), "geo": I.geography(ctx),
         "tac": I.tactics(ctx)}
    r["ops"] = I.opportunities(ctx, r["kb"], r["av"], r["pr"], r["vis"], r["tac"], r["geo"])
    return r


mtime = BRANDS_CSV.stat().st_mtime if BRANDS_CSV.exists() else 0.0
R = build(run_id, mtime, FK, tuple(competitor_keys()), FB)
tr, mk, kb, pe, vi, av, pr, ge, tc = (R[k] for k in ("trust", "market", "kb", "peers", "vis", "av", "pr", "geo", "tac"))
f = pe["focus"]
s = tr["s"]


def section(n: int, title: str, headline: str):
    st.divider()
    st.markdown(f'<p class="kicker">{n:02d}</p>', unsafe_allow_html=True)
    st.subheader(title)
    st.markdown(f'<p class="headline">{headline}</p>', unsafe_allow_html=True)


def hbar(df, x, y, *, highlight=None, label_fmt="{:.1f}%", xtitle="", height=None, color=None, xmax=None):
    d = df.sort_values(x)
    cols = color or [FOCUS_HUE if (highlight is not None and v == highlight) else PEER_HUE for v in d[y]]
    fig = go.Figure(go.Bar(x=d[x], y=d[y], orientation="h", marker=dict(color=cols, line=dict(width=0)),
                           text=[label_fmt.format(v) if pd.notna(v) else "–" for v in d[x]],
                           textposition="outside", cliponaxis=False,
                           hovertemplate="%{y}: %{x:,.1f}<extra></extra>"))
    fig.update_xaxes(title=xtitle, range=[0, (xmax or float(d[x].max() or 1)) * 1.2])
    fig.update_yaxes(title=None)
    return style_fig(fig, height=height or max(200, 27 * len(d) + 60), legend=False, xgrid=True)


# ============================================================================ header
st.title(f"{FB} on Blinkit")
st.caption(f"Skincare + Makeup · crawl `{run_id}` · {int(s.pincodes)} pincodes across {int(s.cities)} metros · "
           f"{int(s.cards):,} shelf listings · {int(s.brands)} brands · {int(s.skus):,} SKUs")

ok = sum(c[1] for c in tr["checks"])
with st.expander(f"{'✅' if tr['all_ok'] else '⚠️'}  Data verified — {ok} of {len(tr['checks'])} integrity checks pass. "
                 "What was checked, and three things to keep in mind", expanded=not tr["all_ok"]):
    st.dataframe(pd.DataFrame(tr["checks"], columns=["check", "passed", "result"]), hide_index=True,
                 width="stretch", column_config={"passed": st.column_config.CheckboxColumn("pass")})
    for cv in tr["caveats"]:
        st.markdown(f"- {cv}")

if f is None:
    st.warning(f"**{FB} is not listed in this crawl.** Sections below describe the K-beauty field it would enter.")

# ============================================================================ verdict
st.markdown('<p class="kicker">The verdict</p>', unsafe_allow_html=True)
if f is not None:
    t = pe["t"]
    bigger = t[t["products"] > f.products]
    rv = vi["reviews"]
    lead = rv.iloc[0] if len(rv) else None
    f_rank = int((rv["median_reviews"] > rv[rv["brand_key"] == FK]["median_reviews"].iloc[0]).sum()) + 1 \
        if FK in set(rv["brand_key"]) else None
    fp = pr["promo"][pr["promo"]["brand_key"] == FK]
    # Compare availability only against brands with a real range: a 1-product brand that happens to
    # be in stock scores 100% and would make any genuine leader look second-rate.
    ranged = t[t["products"] >= 5]
    best = ranged.sort_values("availability", ascending=False).iloc[0] if len(ranged) else None
    if best is None:
        avail_line = "."
    elif best["brand_key"] == FK:
        avail_line = f" — the best of any K-beauty brand with 5+ products (next: {ranged.sort_values('availability', ascending=False).iloc[1]['brand']}, " \
                     f"{ranged.sort_values('availability', ascending=False).iloc[1]['availability']:.0f}%)." if len(ranged) > 1 else "."
    else:
        avail_line = f", against {best['brand']}'s {best['availability']:.0f}%."
    bullets = [
        f"**Distribution is solved.** {FB} is listed in **{int(f.pincodes)} of {pe['pins']}** pincodes, "
        f"with **{f.availability:.0f}%** of its SKUs in stock{avail_line}",
        f"**The range is thin.** {int(f.products)} products across {int(f.categories)} sub-categories — "
        + (f"{len(bigger)} K-beauty brands carry more, led by {bigger.iloc[0]['brand']} with {int(bigger.iloc[0]['products'])}."
           if len(bigger) else "the widest in K-beauty."),
    ]
    if lead is not None and f_rank:
        ratio = lead["median_reviews"] / max(rv[rv["brand_key"] == FK]["median_reviews"].iloc[0], 1)
        bullets.append(
            f"**It ranks low because it has few reviews.** Blinkit's bestseller sort tracks review volume in every "
            f"sub-category. {FB}'s products have a median of **{int(rv[rv['brand_key'] == FK]['median_reviews'].iloc[0])} "
            f"reviews** — #{f_rank} of {len(rv)} K-beauty brands — against {lead['brand']}'s **{int(lead['median_reviews'])}** "
            f"({ratio:.0f}×).")
    if pd.notna(pr["focus_unit_median"]) and len(fp):
        bullets.append(
            f"**It is premium without acting like it.** Per 100 g/ml it costs **{pr['focus_unit_median'] / 100:.1f}×** "
            f"the shelf median, yet only **{fp.iloc[0]['on_promo']:.0f}%** of its listings carry an offer, on a shelf "
            f"where **{pr['shelf_promo']['on_promo']:.0f}%** do.")
    for b in bullets:
        st.markdown(f"- {b}")

    k = st.columns(6)
    k[0].metric("Distribution", f"{int(f.pincodes)}/{pe['pins']}", help="Pincodes with at least one listing.")
    k[1].metric("Availability", f"{f.availability:.0f}%", help="Share of SKUs in stock, every pack size counted.")
    k[2].metric("Products", int(f.products), help="Distinct products on the shelf (pack sizes not counted).")
    k[3].metric("Share of shelf", f"{f.share:.2f}%", help="Our listings ÷ every listing crawled.")
    k[4].metric("Median reviews", f"{int(f.median_reviews) if pd.notna(f.median_reviews) else 0}",
                help="Median review count per product — the demand signal Blinkit ranks on.")
    k[5].metric("Price / 100g vs shelf", f"{pr['focus_unit_median'] / 100:.1f}×" if pd.notna(pr["focus_unit_median"]) else "–",
                help="Median price per 100 g/ml relative to each sub-category's shelf median.")

# ============================================================================ actions
st.divider()
st.markdown('<p class="kicker">What to do</p>', unsafe_allow_html=True)
st.subheader("Recommended moves, highest impact first")
ops = R["ops"]
if not ops:
    st.success("No gaps flagged.")
else:
    for i in range(0, len(ops), 2):
        cols = st.columns(2)
        for col, o in zip(cols, ops[i:i + 2]):
            with col.container(border=True):
                st.markdown(f'<p class="area">{o["area"]}</p><p class="move">{o["move"].replace("**", "")}</p>'
                            f'<p class="why">{o["why"]}</p>', unsafe_allow_html=True)

# ============================================================================ 1 market
cls = mk["cls"].copy()
loc = cls[cls["cls"] == "Local"]
kcls = cls[cls["cls"] == "Korean"]
mo, mc = mk["most_open"], mk["most_closed"]
top_leader = mk["leaders"].iloc[0]
section(1, "The shelf: who owns Blinkit beauty",
        f"A typical dark store carries <b>{mk['per_store']:,.0f}</b> Skincare and Makeup listings. "
        f"<b>Indian brands own {float(loc['share'].iloc[0]) if len(loc) else 0:.0f}%</b> of them and "
        f"{float(loc['top10_share'].iloc[0]) if len(loc) else 0:.0f}% of the top-10 slots; K-beauty holds "
        f"<b>{float(kcls['share'].iloc[0]) if len(kcls) else 0:.1f}%</b>. {top_leader['brand']} leads "
        f"{int(top_leader['categories_led'])} sub-categories outright.")
c1, c2 = st.columns([2, 3])
with c1:
    cls["cls"] = pd.Categorical(cls["cls"], CLASSES, ordered=True)
    d = cls.sort_values("cls")
    fig = go.Figure()
    fig.add_bar(name="share of all listings", y=d["cls"].astype(str), x=d["share"], orientation="h",
                marker_color=[CLASS_COLORS[c] for c in d["cls"].astype(str)], text=[f"{v:.1f}%" for v in d["share"]],
                textposition="outside", cliponaxis=False)
    fig.add_bar(name="share of top-10 slots", y=d["cls"].astype(str), x=d["top10_share"], orientation="h",
                marker_color=[CLASS_COLORS[c] for c in d["cls"].astype(str)], marker_pattern_shape="/",
                marker_opacity=0.55, text=[f"{v:.1f}%" for v in d["top10_share"]], textposition="outside", cliponaxis=False)
    fig.update_layout(barmode="group")
    fig.update_xaxes(title="% of listings", range=[0, float(d[["share", "top10_share"]].max().max()) * 1.25])
    fig.update_yaxes(title=None, autorange="reversed")
    st.plotly_chart(style_fig(fig, height=300, xgrid=True), width="stretch")
    st.caption("Solid = share of all listings; hatched = share of the top-10 positions. Local brands over-index "
               "on the slots that get seen.")
with c2:
    cats = mk["cats"].copy()
    cats = cats.merge(mk["conc"][["subcategory", "hhi", "leader", "leader_share"]], on="subcategory")
    # Neutral cool/warm tints: Skincare vs Makeup is structure, not a competitor, so it must not borrow
    # the focus blue or a class colour from the chart sitting beside it.
    fig = px.bar(cats, x="cards", y="subcategory", color="top_category", orientation="h",
                 color_discrete_map={"Skincare": "#9aa9bb", "Makeup": "#d2bf9f"},
                 category_orders={"subcategory": cats.sort_values("cards", ascending=False)["subcategory"].tolist()},
                 hover_data={"brands": True, "leader": True, "leader_share": ":.1f", "hhi": ":.0f"})
    fig.update_traces(marker_line_width=0)
    fig.update_xaxes(title="listings across all stores")
    fig.update_yaxes(title=None)
    st.plotly_chart(style_fig(fig, height=430, xgrid=True), width="stretch")
    st.caption("Sub-categories by size, largest first. Hover for brand count and who leads each.")
st.markdown(f"**Easiest shelf to enter: {mo['subcategory']}** — {int(mo['brands'])} brands and the leader "
            f"({mo['leader']}) holds just {mo['leader_share']:.1f}%. **Hardest: {mc['subcategory']}** — "
            f"{mc['leader']} alone holds {mc['leader_share']:.0f}% and the top three {mc['top3']:.0f}%.")

# ============================================================================ 2 K-beauty
seg = kb["seg"]
strong = seg[seg["k_share"] > 0].head(3)
kk = kb["k"]
section(2, "K-beauty on Blinkit: a small, premium, under-stocked segment",
        f"<b>{int(kk['brands'])} Korean brands</b> hold <b>{kk['share']:.1f}%</b> of the shelf at a median "
        f"<b>₹{kk['k_price']:,.0f}</b> — {kk['k_price'] / kk['local_price']:.1f}× the Indian median of "
        f"₹{kk['local_price']:,.0f}. Their strongest shelves are "
        + ", ".join(f"{r.subcategory} ({r.k_share:.0f}%)" for r in strong.itertuples())
        + (f"; they are absent from {', '.join(kb['absent'])}." if kb["absent"] else "."))
c1, c2 = st.columns(2)
with c1:
    d = seg[seg["k_share"] > 0].copy()
    fig = go.Figure()
    # One combined label per row, on the longer bar. Labelling both overlaid bars made them collide
    # wherever the two shares were close ("1.7%2.6%").
    fig.add_bar(name="all K-beauty", y=d["subcategory"], x=d["k_share"], orientation="h", marker_color=PEER_HUE,
                text=[f"{k:.1f}%" + (f"  ·  us {fv:.1f}%" if fv >= 0.05 else "  ·  us 0")
                      for k, fv in zip(d["k_share"], d["focus_share"])],
                textposition="outside", cliponaxis=False, textfont=dict(size=11),
                hovertemplate="%{y}<br>K-beauty %{x:.2f}%<extra></extra>")
    fig.add_bar(name=FB, y=d["subcategory"], x=d["focus_share"], orientation="h", marker_color=FOCUS_HUE,
                hovertemplate="%{y}<br>" + FB + " %{x:.2f}%<extra></extra>")
    fig.update_layout(barmode="overlay")
    fig.update_traces(marker_line_width=0)
    fig.update_xaxes(title="% of the sub-category shelf", range=[0, float(d["k_share"].max()) * 1.55])
    fig.update_yaxes(title=None, autorange="reversed")
    st.plotly_chart(style_fig(fig, height=max(300, 26 * len(d) + 80), xgrid=True), width="stretch")
    st.caption(f"Grey = all K-beauty; blue = {FB}. Rows where the grey bar is long and the blue is empty are "
               "shelves K-beauty already sells on that we don't.")
with c2:
    b = kb["bands"].melt(id_vars=["cls", "med"], var_name="band", value_name="pct")
    b = b[b["cls"].isin(["Korean", "Local", "Global"])]
    fig = px.bar(b, x="band", y="pct", color="cls", barmode="group", color_discrete_map=CLASS_COLORS,
                 category_orders={"cls": ["Korean", "Global", "Local"],
                                  "band": ["Under ₹200", "₹200–400", "₹400–800", "₹800–1.5k", "₹1.5k+"]})
    fig.update_traces(marker_line_width=0)
    fig.update_yaxes(title="% of the class's listings")
    fig.update_xaxes(title=None)
    st.plotly_chart(style_fig(fig, height=320), width="stretch")
    pa = kb["avail"].set_index("cls")["avail"]
    pm = kb["promo"].set_index("cls")
    st.caption(f"K-beauty is **bimodal** — cheap single sheet masks and a premium ₹800+ core, with little in between "
               f"where Indian brands live. It also has the **lowest availability of any class** "
               f"({pa.get('Korean', float('nan')):.0f}% vs {pa.max():.0f}% for the best) and **discounts least** "
               f"({pm.loc['Korean', 'on_promo']:.0f}% of listings on offer vs {pm['on_promo'].max():.0f}%).")
ks = kb["kstyle"]
if len(ks):
    with st.container(border=True):
        st.markdown(f"**The 'Korean-style' wave.** Beyond the real K-brands, **{len(ks)} other brands** sell products "
                    f"marketed as *Korean* — **{kb['kstyle_cards']:,} listings**, "
                    f"{kb['kstyle_cards'] / max(float(f.cards) if f is not None else 1, 1):.1f}× {FB}'s entire footprint, "
                    f"typically at a fraction of the price. {ks.iloc[0]['brand']} alone has {int(ks.iloc[0]['cards'])} "
                    "listings. This is who a shopper searching for 'Korean skincare' also meets.")
        st.dataframe(ks.head(8)[["brand", "cards", "products", "med_price", "example"]], hide_index=True, width="stretch",
                     column_config={"med_price": st.column_config.NumberColumn("median ₹", format="₹%.0f"),
                                    "example": st.column_config.TextColumn("example product", width="large")})

# ============================================================================ 3 peers
t = pe["t"].copy()
if f is not None:
    fcm = pe["catmap"][pe["catmap"]["brand"] == FB].sort_values("n", ascending=False)
    conc_line = (f" <b>{int(fcm.iloc[0]['n'])} of its {int(f.products)} products</b> sit in one sub-category, "
                 f"{fcm.iloc[0]['subcategory']} — on Blinkit, {FB} is mostly a {fcm.iloc[0]['subcategory'].lower()} brand."
                 if len(fcm) and fcm.iloc[0]["n"] >= f.products * 0.4 else "")
    section(3, f"{FB} against the K-beauty field",
            f"Every major K-brand has full distribution, so the race is range and visibility. {FB} has "
            f"<b>{int(f.products)} products</b> to {t.iloc[0]['brand']}'s <b>{int(t.iloc[0]['products'])}</b>, and a "
            f"<b>{f.share:.2f}%</b> shelf share — #{int((t['share'] > f.share).sum()) + 1} of {len(t)} K-brands."
            + conc_line)
    c1, c2 = st.columns([2, 3])
    with c1:
        st.plotly_chart(hbar(t.head(10), "share", "brand", highlight=FB, label_fmt="{:.2f}%",
                             xtitle="share of shelf %"), width="stretch")
    with c2:
        cm = pe["catmap"]
        top_b = t.head(6)["brand"].tolist()
        pv = (cm[cm["brand"].isin(top_b)].pivot_table(index="subcategory", columns="brand", values="n", fill_value=0)
              .reindex(columns=[b for b in top_b if b in cm["brand"].unique()]))
        pv = pv.loc[pv.sum(axis=1).sort_values(ascending=False).index]
        fig = px.imshow(pv.values, x=pv.columns.tolist(), y=pv.index.tolist(), text_auto=True, aspect="auto",
                        color_continuous_scale=["#f7f7f5", "#cde2fb", "#6da7ec", "#2a78d6", "#184f95"])
        fig.update_traces(xgap=2, ygap=2, hovertemplate="%{x} · %{y}: %{z} products<extra></extra>")
        fig.update_xaxes(side="top", title=None)
        fig.update_yaxes(title=None)
        fig.update_layout(coloraxis_showscale=False)
        st.plotly_chart(style_fig(fig, height=max(320, 24 * len(pv) + 90), legend=False), width="stretch")
        st.caption("Products per sub-category. Empty cells in our column, filled in a rival's, are range gaps.")
    st.dataframe(t[["brand", "products", "skus", "categories", "pincodes", "availability", "share", "median_rank",
                    "top10_slots", "median_price", "avg_discount", "median_reviews"]],
                 hide_index=True, width="stretch",
                 column_config={"availability": st.column_config.ProgressColumn("in stock", min_value=0, max_value=100, format="%.0f%%"),
                                "share": st.column_config.NumberColumn("shelf %", format="%.2f%%"),
                                "median_rank": st.column_config.NumberColumn("median rank", format="%.0f"),
                                "median_price": st.column_config.NumberColumn("median ₹", format="₹%.0f"),
                                "avg_discount": st.column_config.NumberColumn("avg disc", format="%.1f%%"),
                                "median_reviews": st.column_config.NumberColumn("median reviews", format="%.0f")})

# ============================================================================ 4 visibility
rv = vi["reviews"]
if len(rv):
    fr = rv[rv["brand_key"] == FK]
    section(4, "Why it ranks low: reviews drive the shelf",
            f"Blinkit sorts every category by 'bestsellers'. Across all {len(vi['corr'])} sub-categories, a product's "
            f"position correlates <b>{vi['r_max']:.2f} to {vi['r_min']:.2f}</b> with its review count — more reviews, "
            f"higher on the shelf, every time. "
            + (f"{FB}'s median of <b>{int(fr.iloc[0]['median_reviews'])} reviews</b> puts it "
               f"<b>#{int((rv['median_reviews'] > fr.iloc[0]['median_reviews']).sum()) + 1} of {len(rv)}</b> K-brands."
               if len(fr) else ""))
    c1, c2 = st.columns(2)
    with c1:
        # The focus label sits below its point so it can't collide with a neighbour's (it overlapped
        # Beauty of Joseon's when both were placed above).
        fig = go.Figure(go.Scatter(
            x=rv["median_reviews"], y=rv["median_rank"], mode="markers+text", text=rv["brand"],
            textposition=["bottom center" if k == FK else "top center" for k in rv["brand_key"]],
            textfont=dict(size=11, color=[FOCUS_HUE if k == FK else INK["secondary"] for k in rv["brand_key"]]),
            marker=dict(size=[max(10, min(38, p * 1.4)) for p in rv["products"]],
                        color=[FOCUS_HUE if k == FK else PEER_HUE for k in rv["brand_key"]],
                        line=dict(width=2, color="#ffffff")),
            customdata=rv[["products", "top10_rate"]].values,
            hovertemplate="%{text}<br>median reviews %{x:,.0f}<br>median rank %{y:.0f}"
                          "<br>%{customdata[0]} products · %{customdata[1]:.0f}% in top 10<extra></extra>"))
        fig.update_xaxes(title="median reviews per product (log)", type="log")
        fig.update_yaxes(title="median shelf position (lower = better)", autorange="reversed")
        st.plotly_chart(style_fig(fig, height=380, legend=False), width="stretch")
        st.caption("Bubble size = number of products. Up and to the right is winning.")
    with c2:
        fp = vi["fp"].copy()
        fp["label"] = fp["product_name"].str.replace(FB, "", regex=False).str.strip().str.slice(0, 42)
        fig = go.Figure(go.Bar(x=fp["median_rank"], y=fp["label"], orientation="h",
                               marker=dict(color=[FOCUS_HUE if r <= 40 else PEER_HUE for r in fp["median_rank"]],
                                           line=dict(width=0)),
                               customdata=fp[["reviews", "pincodes", "subcategory"]].values,
                               hovertemplate="%{y}<br>median rank %{x:.0f}<br>%{customdata[0]} reviews · "
                                             "%{customdata[1]} stores<br>%{customdata[2]}<extra></extra>"))
        fig.update_xaxes(title="median shelf position (lower = better)")
        fig.update_yaxes(title=None, autorange="reversed")
        st.plotly_chart(style_fig(fig, height=max(320, 24 * len(fp) + 70), legend=False, xgrid=True), width="stretch")
        st.caption(f"Every {FB} product by median rank. Blue = inside the top 40, where most shoppers look.")

# ============================================================================ 5 availability
oos = av["oos"]
if len(oos):
    w = oos.iloc[0]
    cw = av["city"].dropna(subset=["focus"]).sort_values("focus")
    section(5, "Availability: strong overall, one product badly dark",
            f"<b>{w['product_name']}</b> is out of stock in <b>{int(w['dark_in'])} of {int(w['listed_in'])}</b> stores "
            f"that list it ({w['avail']:.0f}% available). By city, {FB} is weakest in <b>{cw.iloc[0]['city']}</b> "
            f"({cw.iloc[0]['focus']:.0f}%) and strongest in {cw.iloc[-1]['city']} ({cw.iloc[-1]['focus']:.0f}%). "
            f"Across the market, {av['hidden_pct']:.0f}% of products hide an out-of-stock pack size behind an "
            "in-stock listing card.")
    c1, c2 = st.columns([3, 2])
    with c1:
        d = oos[oos["dark_in"] > 0].copy()
        d["label"] = d["product_name"].str.replace(FB, "", regex=False).str.strip().str.slice(0, 40) + " · " + d["unit"].fillna("")
        fig = go.Figure(go.Bar(x=d["dark_in"], y=d["label"], orientation="h",
                               marker=dict(color=["#d03b3b" if v >= 5 else "#ec835a" if v >= 3 else PEER_HUE for v in d["dark_in"]],
                                           line=dict(width=0)),
                               text=[f"{int(a)} of {int(b)}" for a, b in zip(d["dark_in"], d["listed_in"])],
                               textposition="outside", cliponaxis=False,
                               hovertemplate="%{y}<br>dark in %{x} stores<extra></extra>"))
        fig.update_xaxes(title="stores where out of stock", range=[0, float(d["dark_in"].max()) * 1.3])
        fig.update_yaxes(title=None, autorange="reversed")
        st.plotly_chart(style_fig(fig, height=max(260, 24 * len(d) + 70), legend=False, xgrid=True), width="stretch")
        st.caption("Red = dark in 5+ stores, orange = 3–4. Labels read 'dark in / listed in'.")
    with c2:
        cm_ = av["city"].melt(id_vars="city", value_vars=["market", "kbeauty", "focus"], var_name="who", value_name="avail")
        cm_["who"] = cm_["who"].map({"market": "whole shelf", "kbeauty": "K-beauty", "focus": FB})
        fig = px.bar(cm_, x="avail", y="city", color="who", barmode="group", orientation="h",
                     color_discrete_map={"whole shelf": "#c3c2b7", "K-beauty": PEER_HUE, FB: FOCUS_HUE})
        fig.update_traces(marker_line_width=0)
        fig.update_xaxes(title="% of SKUs in stock", range=[0, 105])
        fig.update_yaxes(title=None)
        st.plotly_chart(style_fig(fig, height=380, xgrid=True), width="stretch")

# ============================================================================ 6 pricing
fu = pr["focus_unit"]
if len(fu):
    pp = pr["promo"]
    fpp = pp[pp["brand_key"] == FK]
    section(6, "Pricing: premium per gram, full price on a discounted shelf",
            f"{FB}'s median listing price looks low — that is its ₹130 single sheet masks. Per 100 g/ml it runs "
            f"<b>{pr['focus_unit_median'] / 100:.1f}× the shelf median</b>, from {fu.min() / 100:.1f}× in "
            f"{fu.idxmin()} to <b>{fu.max() / 100:.1f}× in {fu.idxmax()}</b>. Meanwhile "
            + (f"only <b>{fpp.iloc[0]['on_promo']:.0f}%</b> of its listings carry a discount (avg "
               f"{fpp.iloc[0]['avg_disc']:.1f}%), on a shelf where {pr['shelf_promo']['on_promo']:.0f}% do."
               if len(fpp) else ""))
    c1, c2 = st.columns(2)
    with c1:
        ui = pr["unit_idx"].copy()
        ui = ui.loc[ui.notna().sum(axis=1) >= 1]
        lm = ui.reset_index().melt(id_vars="subcategory", var_name="brand", value_name="idx").dropna()
        lm["x"] = lm["idx"] / 100
        # Focus blue, every peer grey, told apart by marker shape — the same rule as the rest of the
        # page. Giving peers orange/aqua would reuse the Global/Local class colours from section 1.
        order = [FB] + sorted(b for b in lm["brand"].unique() if b != FB)
        fig = px.scatter(lm, x="x", y="subcategory", color="brand", symbol="brand",
                         category_orders={"brand": order},
                         color_discrete_map={b: (FOCUS_HUE if b == FB else "#8d99a6") for b in order},
                         symbol_sequence=["circle", "diamond", "square", "triangle-up", "x"])
        fig.add_vline(x=1, line_dash="dot", line_color=INK["muted"], annotation_text="shelf median",
                      annotation_position="top", annotation_font_color=INK["secondary"])
        fig.update_traces(marker=dict(size=12, line=dict(width=2, color="#ffffff")))
        fig.update_traces(selector=dict(name=FB), marker=dict(size=15))
        ticks = [v for v in (0.5, 1, 2, 3, 5, 10, 20) if lm["x"].min() / 1.5 <= v <= lm["x"].max() * 1.5]
        fig.update_xaxes(title="price per 100 g/ml ÷ shelf median (×)", type="log",
                         tickvals=ticks, ticktext=[f"{v:g}×" for v in ticks])
        fig.update_yaxes(title=None)
        st.plotly_chart(style_fig(fig, height=max(320, 30 * len(ui) + 90), xgrid=True), width="stretch")
        st.caption("Each dot is a brand's median unit price in that sub-category, relative to the shelf. "
                   "Right of the dotted line = more expensive per gram.")
    with c2:
        d = pp.copy()
        fig = go.Figure(go.Bar(x=d["on_promo"], y=d["brand"], orientation="h",
                               marker=dict(color=[FOCUS_HUE if k == FK else PEER_HUE for k in d["brand_key"]],
                                           line=dict(width=0)),
                               text=[f"{v:.0f}%" for v in d["on_promo"]], textposition="outside", cliponaxis=False,
                               customdata=d[["avg_disc", "med_price"]].values,
                               hovertemplate="%{y}<br>%{x:.0f}% of listings discounted<br>avg %{customdata[0]:.1f}% off"
                                             "<br>median ₹%{customdata[1]:,.0f}<extra></extra>"))
        fig.add_vline(x=float(pr["shelf_promo"]["on_promo"]), line_dash="dot", line_color=INK["muted"],
                      annotation_text="whole shelf", annotation_position="top", annotation_font_color=INK["secondary"])
        fig.update_xaxes(title="% of listings carrying a discount", range=[0, 118])
        fig.update_yaxes(title=None, autorange="reversed")
        st.plotly_chart(style_fig(fig, height=max(300, 24 * len(d) + 70), legend=False, xgrid=True), width="stretch")
        st.caption("K-beauty brands by promo participation. Most premium K-brands never discount; "
                   "The Face Shop discounts everything.")

# ============================================================================ 7 geography
gs = ge["stores"]
if len(gs) and gs["focus_products"].max() > 0:
    lo, hi = gs.iloc[0], gs.sort_values("focus_products").iloc[-1]
    gc = ge["city"]
    section(7, "Geography: the same brand, a different range in every store",
            f"{FB}'s range varies <b>{hi['focus_products'] / max(lo['focus_products'], 1):.1f}×</b> between stores — "
            f"<b>{int(lo['focus_products'])} products</b> in {lo['area']}, {lo['city']} vs <b>{int(hi['focus_products'])}</b> "
            f"in {hi['area']}, {hi['city']}. {gc.iloc[0]['city']} is the thinnest city on average "
            f"({gc.iloc[0]['focus_products']:.1f} products per store).")
    d = gs.copy()
    d["label"] = d["city"].str.slice(0, 9) + " · " + d["area"].str.slice(0, 22)
    fig = go.Figure(go.Bar(x=d["focus_products"], y=d["label"], orientation="h",
                           marker=dict(color=[FOCUS_HUE if v >= d["focus_products"].median() else PEER_HUE
                                              for v in d["focus_products"]], line=dict(width=0)),
                           text=[str(int(v)) for v in d["focus_products"]], textposition="outside", cliponaxis=False,
                           customdata=d[["pincode", "cards", "k_share"]].values,
                           hovertemplate="%{y} (%{customdata[0]})<br>%{x} of our products"
                                         "<br>store shelf %{customdata[1]:,} listings · K-beauty %{customdata[2]:.1f}%<extra></extra>"))
    fig.update_xaxes(title=f"{FB} products stocked", range=[0, float(d["focus_products"].max()) * 1.2])
    fig.update_yaxes(title=None, autorange="reversed")
    st.plotly_chart(style_fig(fig, height=max(360, 21 * len(d) + 70), legend=False, xgrid=True), width="stretch")
    st.caption("Every crawled store, thinnest range at the top. Grey = below our median store; those are the gaps.")

# ============================================================================ 8 tactics
cr = tc["cross"]
if len(cr):
    top = cr.iloc[0]
    kcross = cr[cr["cls"] == "Korean"]
    pk_ = tc["packs"]
    section(8, "Competitor playbook: tactics we are not using",
            f"<b>Cross-listed combo packs.</b> A bundle sits on every shelf it touches, multiplying listings without new "
            f"products. {top['brand']} earns <b>{top['pct_from_combos']:.0f}%</b> of its listings this way"
            + (f"; the leading K-brand user is {kcross.iloc[0]['brand']} ({kcross.iloc[0]['pct_from_combos']:.0f}%)"
               if len(kcross) else "")
            + f". {FB} has <b>{tc['focus_combos']}</b> combos.")
    c1, c2 = st.columns(2)
    with c1:
        d = cr.head(10).copy()
        fig = go.Figure(go.Bar(x=d["pct_from_combos"], y=d["brand"], orientation="h",
                               marker=dict(color=[CLASS_COLORS.get(c, PEER_HUE) for c in d["cls"]], line=dict(width=0)),
                               text=[f"{v:.0f}%" for v in d["pct_from_combos"]], textposition="outside", cliponaxis=False,
                               customdata=d[["combos", "combo_cards", "cls"]].values,
                               hovertemplate="%{y} (%{customdata[2]})<br>%{x:.0f}% of listings from %{customdata[0]} "
                                             "combos<br>%{customdata[1]} listings<extra></extra>"))
        fig.update_xaxes(title="% of the brand's listings coming from cross-listed combos", range=[0, 90])
        fig.update_yaxes(title=None, autorange="reversed")
        st.plotly_chart(style_fig(fig, height=360, legend=False, xgrid=True), width="stretch")
        st.caption("Coloured by classification: violet = Korean, aqua = Local, orange = Global, grey = unclassified.")
    with c2:
        if len(pk_):
            st.plotly_chart(hbar(pk_, "sizes_per_product", "brand", highlight=FB, label_fmt="{:.2f}",
                                 xtitle="pack sizes offered per product", xmax=float(pk_["sizes_per_product"].max())),
                            width="stretch")
            fpk = pk_[pk_["brand_key"] == FK]
            st.caption("**Pack-size choice.** "
                       + (f"{FB} offers {fpk.iloc[0]['sizes_per_product']:.2f} sizes per product — "
                          if len(fpk) else "")
                       + f"{pk_.iloc[0]['brand']} leads at {pk_.iloc[0]['sizes_per_product']:.2f}. Extra sizes add "
                       "price points and a second card in the size picker.")

# ============================================================================ 9 change
st.divider()
st.markdown('<p class="kicker">09</p>', unsafe_allow_html=True)
st.subheader("What changed since the last crawl")
if len(ids) < 2 or ids.index(run_id) == len(ids) - 1:
    st.info("This is the first crawl, so there is nothing to compare yet. From next week this section shows new "
            "listings, delistings, stock flips and price moves for the focus brand and its peers.")
else:
    st.info("Week-over-week detail is on **Explore & data → Changes**.")
